version: '3.3'
services:
    playout:
        devices:
            - /dev/nvidia-caps
            - /dev/nvidia0
            - /dev/nvidiactl
            - /dev/nvidia-modeset
            - /dev/nvidia-uvm
            - /dev/nvidia-uvm-tools
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - /root/playout/conf:/etc/ffplayout:rw
            - /root/playout/db:/usr/share/ffplayout/db:rw
            - /logos/public:/usr/share/ffplayout/public:rw
            - /var/lib/ffplayout/media1G/hmsc:/var/lib/ffplayout/tv-media:rw  
        ports:
            - '8181:8787'
            - '2221:22'
        privileged: true
        restart: always
        image: cooliobr/nvidia_rocklinux:8787
        networks:
          network:
            ipv4_address: 172.21.0.2
        deploy:
          resources:
            limits:
              cpus: "8"
              memory: '16gb'
        environment:
            - TZ=America/Sao_Paulo
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
        command:
            - '/usr/sbin/init'
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
          #volumes:
          #/media/Data/hallo:
          #storage_opt:
          #size: '2048G'              
