version: '3'
services:
    proxy:
        restart: always
        privileged: true
        environment:
            - TZ=America/Sao_Paulo
            - container=docker
            - VIDEO_GID=44
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro    
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - /opt/ssl:/opt/ssl:rw
            - /opt/conf:/opt/conf:rw
        ports:
            - '21978:22'
            - '280:80'
            - '25000:5000'
            - '22086:2086'
            - '2443:443'
            - '21935:1935'
        image: cooliobr/astra:v1
        stdin_open: true # docker run -i
        tty: true        # docker run -t

        networks:
          network:
            ipv4_address: 172.22.0.2
        deploy:
          resources:
            limits:
              cpus: "8"
              memory: '16gb'
        build:
          context: .
          dockerfile: ./Dockerfile
          shm_size: '24gb'
        shm_size: '24gb'

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
          #volumes:
          #/media/Data/hallo:
          #storage_opt:
          #size: '2048G'
