version: '3'
services:
    proxy:
        restart: always
        privileged: true
        environment:
            - TZ=America/Sao_Paulo
            - container=docker
            - VIDEO_GID=44
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
        cap_add:
            - SYS_ADMIN              
        devices:
            - /dev/nvidia-caps
            - /dev/nvidia0
            - /dev/nvidiactl
            - /dev/nvidia-modeset
            - /dev/nvidia-uvm
            - /dev/nvidia-uvm-tools
            - '/dev/dri/card0:/dev/dri/card0'
            - '/dev/dri/renderD128:/dev/dri/renderD128'              
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro    
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
            - /opt/ssl:/opt/ssl:rw
            - /opt/conf:/opt/conf:rw
            - /dev/shm:/usr/share/nginx/live:rw
        ports:
            - '21978:22'
            - '280:80'
            - '25000:5000'
            - '22086:2086'
            - '2443:443'
            - '21935:1935'
        image: cooliobr/serversat:sat01
        #image: cooliobr/astra:v1
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        #network_mode: host
        networks:
          network:
            ipv4_address: 172.22.0.2
        #deploy:
        #  resources:
        #    limits:
        #      cpus: "2"
        #      memory: '6gb'
        #build:
        #  context: .
        #  dockerfile: ./Dockerfile
        #  shm_size: '24gb'
        shm_size: '24gb'
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1


          #volumes:
          #/media/Data/hallo:
          #storage_opt:
          #size: '2048G'
